services:
  workspace-api:
    build:
      context: ./workspace-api
      dockerfile: ./Dockerfile
    container_name: plutus-workspace-api
    restart: always
    environment:
      DATABASE_URL: postgres://postgres.kkfwybnsgtvfvxaxjsaz:Matkhaumoi2%40%40@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
      NEO4J_URI: neo4j+s://9f328ab7.databases.neo4j.io
      NEO4J_USER: 9f328ab7
      NEO4J_PASSWORD: pEhHSlUkMeLqmZ1gs3i59uv40X5dqnKskpkqn93j_iE
      NODE_ENV: production
      PORT: 3000
      VOYAGE_API_KEY: ${VOYAGE_API_KEY}
    ports:
      - "7140:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

